name: Assign Issue to Team Member
on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue manually
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignees = ["shakarr"]; // Cambia con los usuarios reales
            const assignee = assignees[Math.floor(Math.random() * assignees.length)];
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: [assignee]
            });
